language: c
cache:
  directories:
    - $HOME/Library/Caches/Homebrew/style
    - $HOME/Library/Caches/Homebrew/tests
    - $HOME/Library/Homebrew/vendor/bundle
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      osx_image: xcode9.2
    - os: linux
      compiler: gcc
      sudo: false

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      MACOS="1";
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY";
    else
      LINUX="1";
      export PATH="$PWD/bin:$PATH";
    fi
  # umask 022 fixes Linux `brew tests` failures;
  - if [ "$LINUX" ]; then
      umask 022;
    fi
  # trigger vendored ruby installation
  - brew help
  - if [ "$MACOS" ]; then
      mv "$HOMEBREW_REPOSITORY/Library/Taps" "$PWD/Library";
      sudo rm -rf "$HOMEBREW_REPOSITORY";
      sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY";
    else
      HOMEBREW_CORE_TAP_DIR="$(brew --repo "homebrew/core")";
      mkdir -p "$HOMEBREW_CORE_TAP_DIR";
    fi
  - if [ "$MACOS" ]; then
      travis_retry git -C Library/Taps/homebrew/homebrew-core fetch --depth=1 origin;
    fi
  - travis_retry git clone --depth=1 https://github.com/Homebrew/homebrew-test-bot Library/Taps/homebrew/homebrew-test-bot
  - if [ "$LINUX" ]; then
      HOMEBREW_TEST_BOT_TAP_DIR="$(brew --repo "homebrew/test-bot")";
      ln -s "$HOMEBREW_TEST_BOT_TAP_DIR/.git" "$HOMEBREW_TEST_BOT_TAP_DIR/Formula" "$HOMEBREW_CORE_TAP_DIR";
    fi
  # can be removed after 1.5.3 is tagged
  - if [ "$LINUX" ]; then
      export HOMEBREW_FORCE_VENDOR_RUBY=1;
    fi

script:
  - brew test-bot

notifications:
  slack: machomebrew:1XNF7p1JRCdBUuKaeSwsWEc1
